//TropipayAuth — "Login with Tropipay" (OAuth authorization code + PKCE).
// This user-level flow is not documented for API v3 yet, so it keeps the legacy endpoints and the
// exact URLs generated by 1.x (changing them could break redirect urls already registered in Tropipay).
const axios = require('axios');
const Crypto = require('crypto');
const TropipayEndpoints = require('./TropipayEndpoints');
const {normalizeServerUrl} = require('../core/config');
const {TropipayConfigError, fromAxiosError} = require('../core/errors');

const deleteWhiteSpaces = (url) => {
    return url.replace(/\s+/g, '');
};

const jsonToQueryString = (obj) => {
    const queryParams = new URLSearchParams(Object.entries(obj));
    return queryParams.toString();
};

const pick = (...values) => values.find((value) => value !== undefined && value !== null && value !== '');

class TropipayAuth {

    #config;
    #authorizeUrl;
    #authorizationTokenUrl;
    #userProfileUrl;
    #redirectUrl;
    #defaultHeaders;
    #request;

    /**
     * @param {object} [options] - every key falls back to process.env:
     *  clientId (TROPIPAY_CLIENT_ID), clientSecret (TROPIPAY_CLIENT_SECRET), scopes (TROPIPAY_SCOPE_FRONT),
     *  challengeMethod (TROPIPAY_CODE_CHALLENGE_METHOD), serverUrl (TROPIPAY_SERVER), appUrl (APP_URL),
     *  callbackPath (default "/api/auth/callback")
     */
    constructor(options = {}) {
        const env = process.env;
        this.#config = {
            clientId: pick(options.clientId, env.TROPIPAY_CLIENT_ID),
            clientSecret: pick(options.clientSecret, env.TROPIPAY_CLIENT_SECRET),
            scopes: pick(options.scopes, env.TROPIPAY_SCOPE_FRONT),
            challengeMethod: pick(options.challengeMethod, env.TROPIPAY_CODE_CHALLENGE_METHOD),
            tppServerUrl: pick(options.serverUrl, env.TROPIPAY_SERVER),
            appUrl: pick(options.appUrl, env.APP_URL),
            callbackPath: pick(options.callbackPath, '/api/auth/callback'),
            responseType: 'code',
        };

        const required = ['clientId', 'clientSecret', 'scopes', 'challengeMethod', 'tppServerUrl'];
        const missing = required.filter((key) => !this.#config[key]);
        if (missing.length) {
            // Only the names of the missing keys are reported, never the values.
            throw new TropipayConfigError(`TropipayAuth: Missing required TPP configuration: ${missing.join(', ')}`, missing);
        }

        const serverUrl = normalizeServerUrl(this.#config.tppServerUrl);
        this.#redirectUrl = (this.#config.appUrl + this.#config.callbackPath);
        this.#authorizeUrl = serverUrl + TropipayEndpoints.legacy.authorize;
        this.#authorizationTokenUrl = serverUrl + TropipayEndpoints.legacy.token;
        this.#userProfileUrl = serverUrl + TropipayEndpoints.legacy.profile;
        this.#defaultHeaders = {
            'Content-Type': 'application/json',
            Accept: 'application/json',
        };
        this.#request = axios.create({
            headers: this.#defaultHeaders,
            ...(options.httpAdapter ? {adapter: options.httpAdapter} : {}),
        });
    }

    base64URLEncode(str) {
        return str.toString('base64')
            .replace(/\+/g, '-')
            .replace(/\//g, '_')
            .replace(/=/g, '');
    }

    sha256(buffer) {
        return Crypto
            .createHash('sha256')
            .update(buffer)
            .digest();
    }

    /**
     * Builds the Tropipay login url. Store `code_verifier` and `state` (e.g. httpOnly cookies) and
     * compare `state` in the callback before calling GetAuthorizationToken.
     * @param {object} [params] - extra query params appended to the callback url
     * @returns {{url: string, code_verifier: string, state: string}}
     */
    Login(params) {

        const randomBytes = Crypto.randomBytes(64);
        const codeVerifier = this.base64URLEncode(randomBytes);
        const codeChallenge = this.base64URLEncode(this.sha256(codeVerifier));
        const state = Crypto.randomBytes(8).toString('hex');

        const urlToRedirect = `${this.#redirectUrl} ${params ? `?${jsonToQueryString(params ?? {})}&` : ''}`;

        const urlParams = new URLSearchParams({
            response_type: this.#config.responseType,
            client_id: this.#config.clientId,
            code_challenge: codeChallenge,
            code_challenge_method: this.#config.challengeMethod,
            state: state,
            scope: this.#config.scopes,
            redirect_uri: deleteWhiteSpaces(urlToRedirect),
        });

        return {
            url: deleteWhiteSpaces(`${this.#authorizeUrl}?${urlParams.toString()}`),
            code_verifier: codeVerifier,
            state: state,
        };
    }

    /**
     * Exchanges the authorization code for the user token.
     * @param {string} authorizationCode
     * @param {string} codeVerifier
     * @param {string} [redirectUri] - defaults to APP_URL (1.x behaviour)
     * @returns {Promise<object|false>}
     */
    async GetAuthorizationToken(authorizationCode, codeVerifier, redirectUri = this.#config.appUrl) {

        if (!authorizationCode || !codeVerifier) return false;
        try {
            const authorizationTokenResponse = await this.#request.post(
                this.#authorizationTokenUrl,
                {
                    grant_type: 'authorization_code',
                    code: authorizationCode,
                    client_id: this.#config.clientId,
                    client_secret: this.#config.clientSecret,
                    redirect_uri: redirectUri,
                    code_verifier: codeVerifier,
                    scope: this.#config.scopes,
                },
            );
            if (authorizationTokenResponse.status === 200) {
                return authorizationTokenResponse.data;
            }
            return false;
        } catch (error) {
            const tppError = fromAxiosError(error, {method: 'POST', path: TropipayEndpoints.legacy.token});
            console.error('TropipayAuth: GetAuthorizationToken error', tppError.status || tppError.code, tppError.message);
            return false;
        }

    }

    /**
     * Profile of the user that logged in.
     * @returns {Promise<object|false>}
     */
    async GetProfile(accessToken, tokenType = 'Bearer') {
        if (!accessToken) return false;
        try {
            const userProfileResponse = await this.#request.get(
                this.#userProfileUrl,
                {
                    headers: {'Authorization': `${tokenType || 'Bearer'} ${accessToken}`},
                },
            );
            if (userProfileResponse.status === 200) {
                return userProfileResponse.data;
            }
            return false;
        } catch (error) {
            const tppError = fromAxiosError(error, {method: 'GET', path: TropipayEndpoints.legacy.profile});
            console.error('TropipayAuth: GetProfile error', tppError.status || tppError.code, tppError.message);
            return false;
        }
    }
}

module.exports = TropipayAuth;
